routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('reset_password/{token}', ['as' => 'password.reset', function($token)
// {
//     // implement your reset password route here!
// }]);

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/',function () {
   return view('login');
});
Route::get('/admin/list',"AdminController@");
Route::post("/adminlogin", "AdminController@login");
Route::get('/admin/addplace',function(){
   return view('addPlace');
});
Route::post('admin/formadd','AdminController@addPlace');
Route::get('/logout',"AdminController@logout");

Route::get('/list/all','AdminController@postlogin');
Route::resource('currencies', 'CurrencyController');
Route::get('place/{id}','AdminController@place');
Route::get('edit/place/{id}','PlaceController@editPlace');
Route::get('approve/place/{id}','PlaceController@approvePlace');
Route::post('edit/submit','PlaceController@editplacesubmit');
Route::get('delete/place/{id}','PlaceController@deleteplace');
Route::get('delete/currency/{id}/{placeid}','PlaceController@deletecurrency');
Route::get('list/unverified',function (){
   return view('unverified');
});

app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{

    //
    protected $table='currency';

    protected $fillable=['currency_name'];
    //protected $with=['currencyRate'];
    public function currencyRate(){
        return $this->belongsToMany('App\Place','exchange_currency','currency_id','place_id');
    }
}

app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use App\Currency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Session;
use Illuminate\Support\Facades\Redirect;
use View;


class CurrencyController extends Controller
{
    //
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        $currency = Currency::all();

        // load the view and pass the nerds
        return View::make('currency.index')
            ->with('currency', $currency);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('currency.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        //
        $currency = new Currency;
        $currency->currency_name       = Input::get('currency_name');

        $currency->save();

        // redirect
        Session::flash('message', 'Successfully created currency!');
        return \Redirect::to('currencies');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
        $currency = Currency::find($id);

        // show the view and pass the nerd to it
        return View::make('currency.show')
            ->with('currency', $currency);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
        $currency = Currency::find($id);

        // show the edit form and pass the nerd
        return View::make('currency.edit')
            ->with('currency', $currency);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        $currency = Currency::find($id);
        $currency->currency_name       = Input::get('currency_name');
        $currency->save();

        // redirect
        Session::flash('message', 'Successfully updated currency!');
        return Redirect::to('currencies');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $currency = Currency::find($id);
        $currency->delete();

        // redirect

        return Redirect::to('currencies');
        //
    }

    public function getallcurrencies(){
        return Currency::all();
    }

}

resources/views/currency/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/js/lightbox.js"></script>
    <link rel="stylesheet" href="/css/lightbox.css">
    <style>
        body, html, .container-fluid {
            color:white;
            margin:0;
            height: 100%;
            background: linear-gradient(#1891db, #db6218);
            background-image: -webkit-linear-gradient(bottom, #1891db 0%, #db6218 100%);
            background-repeat: no-repeat;
        }
        a{
            color:white;
        }
        a:visited{
            color:white;
        }
        input{
            color:black;
        }
    </style>

    <title>
        Currencies Dashboard
    </title>
</head>
<body>
<div class="container-fluid">
    <div class="row">

        <nav class="navbar navbar-inverse">
            <ul class="nav navbar-nav">
                <li><a href="#">Exchange Companion</a></li>
                <li><a href="/list/all">All Places</a></li>
                <li><a href="/admin/addplace">Add Places</a></li>
                <li><a href="{{ URL::to('currencies') }}">All Currencies</a></li>
                <li><a href="{{ URL::to('currencies/create') }}">Create a Currency</a>
                <li><a href="{{ URL::to('list/unverified') }}">Unverified Places</a>
                <li><a href="/logout">Logout</a></li>
            </ul>

        </nav>
        <div class="container">
            <h1>Create a Currency</h1>

            <form action="{{action('CurrencyController@store')}}" method="post">
                <input type="hidden" name="_token" value="{{ csrf_token() }}" >
            <div class="form-group">
                <label>Currency Name</label>
                <input type="text" placeholder="Currency Name" name="currency_name">
            </div>



            <div class="form-group">
                    <input type="submit" class="btn btn-default" value="Add Currency">
                </div>


            </form>


        </div>
    </div>
</div>



</body>
</html>

resources/views/currency/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/js/lightbox.js"></script>
    <link rel="stylesheet" href="/css/lightbox.css">
    <style>
        body, html, .container-fluid {
            color:white;
            margin:0;
            height: 100%;
            background: linear-gradient(#1891db, #db6218);
            background-image: -webkit-linear-gradient(bottom, #1891db 0%, #db6218 100%);
            background-repeat: no-repeat;
        }
        a{
            color:white;
        }
        a:visited{
            color:white;
        }
        input{
            color:black;
        }
    </style>

    <title>
        Currencies Dashboard
    </title>
</head>
<body>
<div class="container-fluid">
    <div class="row">

        <nav class="navbar navbar-inverse">
            <ul class="nav navbar-nav">
                <li><a href="#">Exchange Companion</a></li>
                <li><a href="/list/all">All Places</a></li>
                <li><a href="/admin/addplace">Add Places</a></li>
                <li><a href="{{ URL::to('currencies') }}">All Currencies</a></li>
                <li><a href="{{ URL::to('currencies/create') }}">Create a Currency</a>
                <li><a href="{{ URL::to('list/unverified') }}">Unverified Places</a>
                <li><a href="/logout">Logout</a></li>
            </ul>

        </nav>
        <div class="container">
            <h1>Edit {{ $currency->currency_name }}</h1>

            <form action="{{url('currencies/'.$currency->id.'/edit')}}" method="POST">
                <input name="_method" type="hidden" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}" >
                <div class="form-group">
                    <label for="Currency Name"></label>
                    <input type="text" name="currency_name" value="{{$currency->currency_name}}">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Edit Currency">
                </div>
            </form>



        </div>
    </div>
</div>



</body>
</html>

resources/views/currency/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/js/lightbox.js"></script>
    <link rel="stylesheet" href="/css/lightbox.css">
    <style>
        body, html, .container-fluid {
            color:white;
            height: 100%;
            margin:0;
            background: linear-gradient(#1891db, #db6218);
            background-image: -webkit-linear-gradient(bottom, #1891db 0%, #db6218 100%);
            background-repeat: no-repeat;
        }
        a{
            color:white;
        }
        a:visited{
            color:white;
        }
    </style>

    <title>
        Currencies Dashboard
    </title>
</head>
<body>
<div class="container-fluid">
    <div class="row">

        <nav class="navbar navbar-inverse">
            <ul class="nav navbar-nav">
                <li><a href="#">Exchange Companion</a></li>
                <li><a href="/list/all">All Places</a></li>
                <li><a href="/admin/addplace">Add Places</a></li>
                <li><a href="{{ URL::to('currencies') }}">All Currencies</a></li>
                <li><a href="{{ URL::to('currencies/create') }}">Create a Currency</a>
                <li><a href="{{ URL::to('list/unverified') }}">Unverified Places</a>
                <li><a href="/logout">Logout</a></li>
            </ul>

        </nav>
        <div class="container">
            <h2>All Currencies</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Currency Name</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($currency as $key => $value)
                        <tr>
                            <td>{{ $value->id }}</td>
                            <td>{{ $value->currency_name }}</td>
                            <td style="display:inline-flex;">
<form method="POST" action="{{ route('currencies.destroy', $value->id) }}">
    <input type="submit" class="btn btn-warning" value="Delete This Currency">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" name="_method" value="DELETE" />

</form>


        <!-- delete the nerd (uses the destroy method DESTROY /nerds/{id} -->
        <!-- we will add this later since its a little more complicated than the other two buttons -->

        <!-- show the nerd (uses the show method found at GET /nerds/{id} -->


        <!-- edit this nerd (uses the edit method found at GET /nerds/{id}/edit -->
        <a class="btn btn-small btn-info" href="{{ URL::to('currencies/' . $value->id . '/edit') }}">Edit this Currency</a>

    </td>


</tr>
@endforeach
</tbody>
</table>
</div>

</div>
</div>
</div>



</body>
</html>

resources/views/currency/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/js/lightbox.js"></script>
    <link rel="stylesheet" href="/css/lightbox.css">
    <style>
        body, html, .container-fluid {
            color:white;
            margin:0;
            height: 100%;
            background: linear-gradient(#1891db, #db6218);
            background-image: -webkit-linear-gradient(bottom, #1891db 0%, #db6218 100%);
            background-repeat: no-repeat;
        }
        a{
            color:white;
        }
        a:visited{
            color:white;
        }
    </style>

    <title>
        Currencies Dashboard
    </title>
</head>
<body>
<div class="container-fluid">
    <div class="row">

        <nav class="navbar navbar-inverse">
            <ul class="nav navbar-nav">
                <li><a href="#">Exchange Companion</a></li>
                <li><a href="/list/all">All Places</a></li>
                <li><a href="/admin/addplace">Add Places</a></li>
                <li><a href="{{ URL::to('currencies') }}">All Currencies</a></li>
                <li><a href="{{ URL::to('currencies/create') }}">Create a Currency</a>
                <li><a href="{{ URL::to('list/unverified') }}">Unverified Places</a>
                <li><a href="/logout">Logout</a></li>
            </ul>

        </nav>
        <div class="container">
            <h1>Showing {{ $currency->name }}</h1>

            <div class="jumbotron text-center">
                <h2>{{ $currency->name }}</h2>
                <p>
                    <strong>Email:</strong> {{ $currency->currency_name }}<br>
                </p>
            </div>

        </div>
    </div>
</div>



</body>
</html>